import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version '1.9.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation libs.kotlin.stdlib

    testImplementation "org.junit.jupiter:junit-jupiter:5.8.2"
    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin
}